### ISSUE TITLE
[1.15.2] Server crash when looking at a watermellon stock

### ISSUE THREAD

**Issue by ProsperCraft** [Geek202/LookAtThat#9] opened 2020-03-11 03:00 UTC
**Describe the bug**
When you look at a watermelon stock the server crashes, remove LAT and it no longer crashes.

Crash report - 
https://gist.github.com/ProsperCraft/927144a392a72e38c08aab92cca7a6e7

From mod author chat in my discord - 

 kwpugh: the StemBlock.func_176481() is old mappings, current mappings have it as 
   @Nullable
   @OnlyIn(Dist.CLIENT)
   protected Item getSeedItem() {
      if (this.crop == Blocks.PUMPKIN) {
         return Items.PUMPKIN_SEEDS;
      } else {
         return this.crop == Blocks.MELON ? Items.MELON_SEEDS : null;
      }
   }

**Comment by Tom-The-Geek** [comment] 2020-03-11 08:02
This issue is similar to #7 and I am looking into the issue as it appears to be a bug with Forge's SAS overrides.

**Comment by Tom-The-Geek** [comment] 2020-03-13 08:35
Also, the note about new/old mappings mean nothing in a runtime environment as function names are not deobfuscated and so the MCP names are used. This means that the bug is caused by sidedness and not outdated mappings on the mod.

**Comment by Tom-The-Geek** [comment] 2020-03-18 17:09
Implemented temporary fix for this and will push to CurseForge tomorrow.

**Comment by Tom-The-Geek** [comment] 2020-06-13 10:53
Forge appears to have fixed the issue in MinecraftForge/MinecraftForge#9114bec. When Forge releases the version containing this fix, I will close this issue.

**Comment by Tom-The-Geek** [comment] 2020-06-13 11:00
Forge has fixed in 1.15.2-31.2.19

**Closed as completed by Tom-The-Geek** 2020-06-13 11:00 UTC
Labels: bug, 1.15.2
