### ISSUE TITLE
[1.16.3]Crash with Pandora's creatures(cross issue post)

### ISSUE THREAD

**Issue by Dontrell94** [Geek202/LookAtThat#15] opened 2020-10-20 12:19 UTC
**Describe the bug**
Placing an end troll box from pandora's creatures throws an error only when loaded with this mod.

**To Reproduce**
1. Place down End Troll box
2. Crash to desktop.

**Expected behavior**
Block places as normal, doesn't crash.

**Additional context**
https://gist.github.com/Dontrell94/815d0fad0742064e2d26b25be470556d

[latest.log](https://github.com/Geek202/LookAtThat/files/5408550/latest.log)

**Comment by Dontrell94** [comment] 2020-10-20 12:26
Tested on a test environment (source of the gist) and Towncraft 2 pack creative single player, both do not crash with removal of mod but maintaining pandora's. And also a link to the original bug report on pandoras github: https://github.com/andrew0030/Pandoras-Creatures/issues/20

**Comment by Tom-The-Geek** [comment] 2020-10-20 15:42
From my research this issue appears to be in the Pandoras Creatures mod, and only manifests itself because of my mod. The issue is inherantly within that mod and a fix in LookAtThat would not solve the underlying problem. I'll close this issue and write up an explanation of what is wrong on the original issue at andrew0030/Pandoras-Creatures#20

**Closed as completed by Tom-The-Geek** 2020-10-20 15:42 UTC
Labels: bug
